### ISSUE TITLE
Using AlpineLinux as host OS to run Java

### ISSUE THREAD

**Issue by lospejos** [frol/docker-alpine-oraclejdk8#12]
I repreated all steps described in dockerfiles on my AlpineLinux, installed in VMWare:
1. https://github.com/frol/docker-alpine-glibc/blob/master/Dockerfile (install glibc into Alpine)
2. https://github.com/frol/docker-alpine-oraclejdk8/blob/master/Dockerfile (install Java 8 into Alpine)
All steps succeeded. But when I run:
`java -version`
I get error:

```
# java -version
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x000064eb8837c000, 2555904, 1) failed; error='Operation not permitted' (errno=1)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 2555904 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /home/user/hs_err_pid3520.log
```

I cannot get how java is running inside your docker container. Did you made some additional kernel or another tunings?
Sorry if this is not directly related to a AlpineJdk8 docker image. I supposed you have experince in running java 8 inside Alpine since you made a nice Docker image :-)

**Comment by frol** [comment]
Docker images by design are using host OS kernel, so this might be the key. Alpine Docker image doesn't use Alpine compiled Linux kernel. Also, I suggest you ensure that you have enough RAM allocated for your VM. Just try to give it as much RAM as you can (though, I don't think there is a point in giving >1GB).

Other than that, I have no other guesses or experience, sorry...

Closing this issue as it is not relevant, but you are welcome to leave your findings and I might help you if I have something in mind.

**Comment by terefang** [comment]
i have had the same problem, changing the grsec kernel to vanilla solved it

**Comment by alessandro-molari** [comment]
@terefang How did you change kernel to vanilla?

**Comment by terefang** [comment]
i used the vanilla install from here https://alpinelinux.org/downloads/
but you may also replace your grsec kernel with a vanilla one using apk on an already installed system

**Comment by ijaychang** [comment]
alpine linux host do sysctl -w kernel.pax.softmode=1，but restart will no effect ,so you should modify the /etc/sysctl.conf
add append a line   
kernel.pax.softmode=1

**Comment by nevercast** [comment]
@jaychang9 Thank you! I wasn't sure how to always apply this on reboot. Its my understanding that individual settings of pax can be modified, do you know which setting I should modify so that only the container is relieved of the PAX restrictions, and not the entire system?
