### ISSUE TITLE
Could the tag of the images include the Java version?

### ISSUE THREAD

**Issue by fbrulotte** [frol/docker-alpine-oraclejdk8#16]
Just a suggestion, would it be possible to produce your images with the java version in it? Something like `8.121-cleaned`.
This would allow for repeatable build using a fixed version of Java and not always using latest Java version when image is pulled.
It would be especially beneficial when you build docker images on multiple machines.
Thanks

**Comment by frol** [comment]
As far as I know, those new releases of JDK 8 are only security/bug fixes, so I don't see a point in leaving old unmaintained versions, and it is too much of a labor work for me. Sorry.

If you really need to pin the image version, use references by digest:

```Dockerfile
FROM frolvlad/alpine-oraclejdk8@sha256:4d44eda497e364121557fbffa654e3147c0b395978cf54b4f05aec25e1549cf1
```

*HINT: Use `docker images --digests` to get the image digest.*
