### ISSUE TITLE
Please tag the repo with OS and JDK versions

### ISSUE THREAD

**Issue by mateusz-myob** [frol/docker-alpine-oraclejdk8#17]
It would be great if you could create a tag that has a locked OS and JDK version, like `3.5_8.121.13` so we could lock our code with that specific tag without risking it getting updated to the newer version of these.

**Comment by frol** [comment]
Good point. I will do that by the next Alpine release (I just don't have much time at the moment).

**Comment by mateusz-myob** [comment]
Thank you :)

**Comment by frol** [comment]
I have added tags for JDK releases (`:8.121.13-slim`, `:8.121.13-cleaned`, `:8.121.13-full`, `:8.131.11-slim`, `:8.131.11-cleaned`, `:8.131.11-full`). Only the latest JDK release tags will receive Alpine upgrades while older JDK releases will stay in a frozen state forever. Thus, I decided not to implement the Alpine version tagging.
