### ISSUE TITLE
Problems with the JDK 131 related release

### ISSUE THREAD

**Issue by xtremebiker** [frol/docker-alpine-oraclejdk8#19]
Hello,

I see you're repushing the JDK 131 related images to the Docker Hub. These days we ran into trouble because we were using the slim image as parent image for our projects and their stop recognizing the docker enviroment variables once updated to 131. There was no problem with 121 images, so yesterday we change our code to stick to them. I was preparing a test project to share with you.

Is it a problem you've already solved with the current push? 

Thanks

**Comment by frol** [comment]
Hi,

I haven't changed much in the images, they have automatically got rebuilt with [the latest commit](https://github.com/frol/docker-alpine-oraclejdk8/commit/2072891a8a3a791cdb224977f9c00168a09520a7), which only touched README.

I have not experienced any problems with the image in any of my projects. A week or so ago I have updated the base image from Alpine 3.5 to the newly released Alpine 3.6, so it might be the cause of the change in behavior. Can you provide a minimal reproducible example so I can help you?

Cheers!

**Comment by PraveenSalitra** [comment]
@xtremebiker: I am facing the same issues in passing --env variables to the docker run command. The springboot container works fine if I use `frolvlad/alpine-oraclejdk8:8.121.13-slim` but it ignores --env variables with `frolvlad/alpine-oraclejdk8:8.131.11-slim`
Were you able to resolve it?

**Comment by xtremebiker** [comment]
@salitrapraveen haven't found time still for it. I'm also using Spring Boot and that's the format of my docker files:

Works:

> FROM frolvlad/alpine-oraclejdk8:8.121.13-slim
ADD app.jar app.jar
ENTRYPOINT exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar

Doesn't pick ENV variables:

> FROM frolvlad/alpine-oraclejdk8:8.131.11-slim
ADD app.jar app.jar
ENTRYPOINT exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar

Still, I made some tests in my local machine and couldn't reproduce it in a project made from scratch (Spring Initializr). Could be even a problem with the Spring Boot version (I'm using 1.4.4 for my production projects) and that specific JDK version. It might be interesting testing with 1.4.4 and more recent boot versions and the 8.131 jdk image.

**Comment by frol** [comment]
I am sorry, but I cannot reproduce the described behaviour on my end:

```Dockerfile
FROM frolvlad/alpine-oraclejdk8:8.131.11-slim

ENTRYPOINT exec echo $JAVA_OPTS
```

```bash
$ docker build -t qq .
$ docker run -it --rm -e JAVA_OPTS=java-test qq
java-test
```
