### ISSUE TITLE
Openssl missing

### ISSUE THREAD

**Issue by mindnuts** [frol/docker-alpine-oraclejdk8#21]
Hi Please add openssl package to fix the issue wherein wget can not download using ssl:

```sh
wget: can't execute 'ssl_helper': No such file or directory
```

**Comment by frol** [comment]
I am not going to do that. This adds extra dependency which is not widely used. Also, you usually want to use `wget` only on the build stage, which means that you can install and drop it in your own `RUN` command and avoid leaving it in the resulting image.

**Comment by mindnuts** [comment]
@frol Fair enough. Then why don't you remove it from the final image? It has wget so i assumed it will work. If wget was removed from this image then i would have chosen to do this:

```sh
apk add --update wget ca-certificates openssl
```

**Comment by frol** [comment]
The installed wget you see in the image is part of Alpine busybox, it is not the one installed separately. In the Dockerfile you can see:

```
apk add --no-cache --virtual=build-dependencies wget ca-certificates unzip
...
apk del build-dependencies
```

**Comment by mindnuts** [comment]
@frol My bad. Thanks for clearing this.
