### ISSUE TITLE
Any thoughts on a docker-alpine-oraclejre8 ?

### ISSUE THREAD

**Issue by PerWiklander** [frol/docker-alpine-oraclejdk8#25]
I'm looking for the smallest possible image for running a single `.jar` web app server.
It feels like we could get this more minimal by removing `javac` and other parts not needed for just running jars.

**Comment by frol** [comment]
Thanks for the suggestion! I agree that it makes sense to use JRE instead of JDK. There is `develar/java` image, but it is a bit outdated... I didn't want to duplicate the existing image, but now I see that my images are much popular and better maintained, so I may introduce JRE in the near future.

**Comment by frol** [comment]
I know you did not expect this to ever happen given the delay, but it did happen: `frolvlad/alpine-oraclejre8` is there (https://github.com/frol/docker-alpine-oraclejre8)!
