### ISSUE TITLE
memory usage is so hign when using alpine-oraclejdk8:slim image

### ISSUE THREAD

**Issue by snakezzl** [frol/docker-alpine-oraclejdk8#29]
I have built two docker images with the same java code, the only difference is the base image, one is based on frolvlad/alpine-oraclejdk8:slim and the other is based on openjdk:8-jdk-alpine. Below is my Dockerfile:

container **testing_ms-dictionary_1** is based on frolvlad/alpine-oraclejdk8:slim image
```
FROM frolvlad/alpine-oraclejdk8:slim
VOLUME /tmp
ADD @project.build.finalName@.jar app.jar
ENV TZ=Asia/Shanghai
ENV JAVA_OPTS="-Xmx512m"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN sh -c 'touch /app.jar'
ENTRYPOINT exec java $JAVA_OPTS -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -Djava.security.egd=file:/dev/./urandom -jar /app.jar
```

container **testing_ms-dictionary2_1** is based on openjdk:8-jdk-alpine image
```
FROM openjdk:8-jdk-alpine
VOLUME /tmp
ADD @project.build.finalName@.jar app.jar
ENV TZ=Asia/Shanghai
ENV JAVA_OPTS="-Xmx512m"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN sh -c 'touch /app.jar'
ENTRYPOINT exec java $JAVA_OPTS -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -Djava.security.egd=file:/dev/./urandom -jar /app.jar
```

I use ctop command to monitor the memory usage, like below:

![image](https://user-images.githubusercontent.com/343500/42751922-f2c81606-891e-11e8-8e01-8f08ffb1b15f.png)

Why the containerm**testing_ms-dictionary_1** based on frolvlad/alpine-oraclejdk8:slim image is so high?

**Comment by frol** [comment]
I have no idea. It might be just the difference between Oracle JDK and OpenJDK or it can be something else, in any case, I only package what Oracle provides.

BTW, consider using JRE instead of JDK if you only need to run a compiled Java application.
