### ISSUE TITLE
Frozen tags

### ISSUE THREAD

**Issue by RichoDemus** [frol/docker-alpine-oraclejdk8#3]
Hi, I currently use your cleaned-tag to refer to your image but I see that you rebuild that tag from time to time, would it be possible for you create some tags that you wont move? like slim-1.0.0 or slim-8u74 or something? :)

**Comment by frol** [comment]
Most of rebuilds are automatically triggered on Alpine image updates. Those are mostly security updates, so I don't really like freezing images without a good reason. What is your use-case? Have you considered using "by digest" image referencing: https://github.com/docker/docker/pull/11109 ?
