### ISSUE TITLE
Create docker hub tags for 8u192 update

### ISSUE THREAD

**Issue by smelchior** [frol/docker-alpine-oraclejdk8#32]
Could you create tags for the 8u192 release?
https://hub.docker.com/r/frolvlad/alpine-oraclejdk8/tags/
Also the 8.181.13-full tag now contains 8u192, that is quite confusing :-)

**Comment by frol** [comment]
Ouch! Sorry about that :(

**Comment by frol** [comment]
I have added the tags, but 8u181 tags are ruined and Oracle does not provide the binaries for the release anymore (HTTP 404).
