### ISSUE TITLE
I think time for an upgrade JDK 8u202

### ISSUE THREAD

**Issue by rasekar2000** [frol/docker-alpine-oraclejdk8#36]
> Location: https://download.oracle.com/otn-pub/java/jdk/8u192-b12/750e1c8617c5452694857ad95c3ee230/jdk-8u192-linux-x64.tar.gz?AuthParam=1547574308_d146acccd8e34c5bc0ed68b52b1fa7e0 [following]
--2019-01-15 17:43:08--  https://download.oracle.com/otn-pub/java/jdk/8u192-b12/750e1c8617c5452694857ad95c3ee230/jdk-8u192-linux-x64.tar.gz?AuthParam=1547574308_d146acccd8e34c5bc0ed68b52b1fa7e0
Connecting to download.oracle.com|23.72.217.186|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-01-15 17:43:08 ERROR 404: Not Found.

https://www.oracle.com/technetwork/java/javase/overview/index.html

End of Public Updates for Oracle JDK 8

Oracle will not post further updates of Java SE 8 to its public download sites for **commercial use after January 2019**. Customers who need continued access to critical bug fixes and security fixes as well as general maintenance for Java SE 8 or previous versions can get long term support through Oracle Java SE Subscription or Oracle Java SE Desktop Subscription. For more information, and details on how to receive longer term support for Oracle JDK 8, please see the Oracle Java SE Support Roadmap.

**Comment by frol** [comment]
> Oracle will not post further updates of Java SE 8 to its public download sites

Oh, great! This means this is going to be the last update for me :)

**Comment by rasekar2000** [comment]
https://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jdk-8u202-linux-x64.tar.gz

8u202 - I am trying.. i guess 202 will be the last one !!

**Comment by frol** [comment]
I have updated both JDK and JRE images to 202. It is now up to Docker Hub to build and publish them.

**Comment by frol** [comment]
@rasekar2000 Thank you for the heads up!

**Comment by rasekar2000** [comment]
Cool .. Appreciated..
