### ISSUE TITLE
frolvlad/alpine-java:jdk8-full images  388MB

### ISSUE THREAD

**Issue by datayang** [frol/docker-alpine-oraclejdk8#38]
Download frolvlad/alpine-java:jdk8-full today, don't know why I don't know why there is 388M. My system is centos7, can you tell me why? Thank you.
![33](https://user-images.githubusercontent.com/18672719/64093697-fa992700-cd8b-11e9-9679-fca404631c88.jpg)

**Comment by frol** [comment]
Full image includes all files from the official JDK bundle. Use cleaned or slim tags to have smaller footprint.
