### ISSUE TITLE
Alpine Java jdk-8u221-b11 docker image

### ISSUE THREAD

**Issue by cz8357** [frol/docker-alpine-oraclejdk8#40]
Dear Sir/Madam,

Can you create jdk-8u221-b11 docker image so that I can download it to my local docker repo?

Can you share the Dockerfile with instructions so that I can create jdk docker image myself?

Thank you for your time and help.

Chen Zhang

**Comment by frol** [comment]
You can find the Dockerfiles in this repo. I cannot distribute the image according to Oracle legal rules. You have to download JDK bundle using your own account and build your own image (I believe, you can put the bundle in your private storage to reuse the Dockerfiles)
