### ISSUE TITLE
Character encoding problem.

### ISSUE THREAD

**Issue by briangebala** [frol/docker-alpine-oraclejdk8#5]
```
import java.text.NumberFormat;
import java.util.Locale;

public class Test {
  public static void main(final String[] args) {
    NumberFormat fmt = NumberFormat.getCurrencyInstance();
    System.out.println(fmt.format(120.00));
  }
}
```

Within the running Alpine Linux Docker container, Oracle JDK 8 prints `¤120.00`.

`env` reports `LANG=C.UTF-8` I tried changing this to `en_US.UTF-8`, but it doesn't help. Instead a `?` is displayed instead of `¤`.

A similar report:
http://stackoverflow.com/questions/35300705/alpine-linux-docker-image-console-encoding-trouble

Any ideas?

Thanks!

**Comment by briangebala** [comment]
I think this is caused by a default locale not being found. Not necessarily a bug per se.

**Comment by frol** [comment]
This looks to me like just a font issue in your terminal. Does it print a proper character when you run the code using, for example, host Java in the same terminal?

**Comment by frol** [comment]
Works fine for me:

``` sh
$ docker run -it --rm -v /tmp:/mnt --workdir /mnt frolvlad/alpine-oraclejdk8:slim sh -c 'javac Test.java && java Test'
$120.00
```

**Comment by briangebala** [comment]
I still get the weird character with that command. I don't believe it's a font issue, as adding default locale info via the command-line fixes the issue:

```
docker run -it --rm -v /tmp:/mnt --workdir /mnt frolvlad/alpine-oraclejdk8:slim sh -c 'javac Test.java && java -Duser.country=FR -Duser.language=fr Test'
120,00 €
```

I noticed the issue originally when my API server running in the Alpine Java 8 container was returning the strange character via a REST endpoint. Adding the same locale config to the API server's JVM arguments corrected the REST endpoint's return value (which was displayed via `curl`) on another system.

An interesting issue. We can close if you like. Thanks for taking some time to look into this.

**Comment by frol** [comment]
Hmm! I can reproduce the "bug"! Though, it is not a bug; the symbol you see is [what it should be on `C.UTF_8` locale](http://stackoverflow.com/questions/10826850/java-string-format-with-currency-symbol)!

P.S. The reason I saw `$` is that I used a previous version of the image on my laptop.
