### ISSUE TITLE
please test with eclipse

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [frol/docker-alpine-oraclejdk8#9]
https://github.com/sgerrand/alpine-pkg-glibc/issues/30

**Comment by frol** [comment]
Closing this as it seems that there is nothing I can do about it.

P.S. I have just realized that since Eclipse is a GUI application, it may require `:full` tag of this image since `:latest`/`:cleaned` and `:slim`.tags have some GUI-related libraries stripped.
